on: 
    push 

jobs:
    demo1:
        runs-on: macos-latest
        steps:
         - name: step1
           run: echo "Olá, mundo"
         - name: step2
           run:
                echo "mensagem 2"
                echo "mensagem 3"
                ls -la

               